micronaut:
  application:
    name: comercio
#dynamo
dynamo:
#  environment: ${DYNAMODB_ENVIRONMENT:`local`}
  endpoint: ${DYNAMODB_CUSTOM_ENDPOINT:`http://localhost:8002`}

aws:
  region: ${AWS_REGION:`us-east-2`}
  accessKeyId: ${AWS_ACCESS_KEY_ID:`fakeMyAccessKeyId`}
  secretKey: ${AWS_SECRET_ACCESS_KEY:`fakeSecretAccessKe`}
