version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8002:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  app-node:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    container_name: app-node
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: 'fakeMyAccessKeyId'
      AWS_SECRET_ACCESS_KEY: 'fakeSecretAccessKe'
    command:
      dynamodb describe-limits --endpoint-url http://dynamodb-local:8002 --region us-west-2
  app:
    image: comercio
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: comercio-grpc
    depends_on:
      - "dynamodb-local"
    ports:
      - "50051:50051"
      - "5005:5005"
    environment:

      AWS_ACCESS_KEY_ID: fakeMyAccessKeyId
      AWS_SECRET_ACCESS_KEY: fakeSecretAccessKe
      AWS_REGION: us-east-2
      ADDCITIONAL_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
    command:
      dynamodb describe-limits --endpoint-url http://dynamodb-local:8002 --region us-west-2

