services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb " #-optimizeDbBeforeStartup -dbPath ./data
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8002:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
#    networks:
#      - production-network
  app:
    image: comercio
    build:
      dockerfile: ./Dockerfile
      context: ./ #./build/libs
    container_name: comercio-grpc
    depends_on:
      - "dynamodb-local"
    ports:
      - "8080:8080"
      - "50051:50051"
      - "5005:5005"
    environment:
      - ADDCITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
#    networks:
#      - production-network

  app-awscli:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    container_name: app-awscli
    ports:
      - "80801:8080"
    environment:
      AWS_ACCESS_KEY_ID: 'fakeMyAccessKeyId'
      AWS_SECRET_ACCESS_KEY: 'fakeSecretAccessKe'
    command:
      dynamodb describe-limits --endpoint-url http://dynamodb-local:8002 --region us-west-2
#  networks:
#    production-network:
#      driver: bridge

